spring.application.name=gameserver
spring.config.import=optional:file:.env[.properties],optional:file:Backend/gameserver/.env[.properties]
app.base-url=${APP_BASE_URL:http://localhost:8080}

# 1. PostgreSQL 연결 설정
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/cooking_game}
spring.datasource.username=${DB_USERNAME:game_manager}
spring.datasource.password=${DB_PASSWORD:ssafy7}

# 2. JPA/Hibernate 설정
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# 커넥션 마름 현상 방지 설정(서버 과부하를 막기 위해 설정)
spring.jpa.open-in-view=false

# PostgreSQL 방언 설정
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# 3. 드라이버 설정
spring.datasource.driver-class-name=org.postgresql.Driver

# 4. 메일 설정 (Naver SMTP)
spring.mail.host=smtp.naver.com
spring.mail.port=465
spring.mail.username=${NAVER_ID}
spring.mail.password=${NAVER_APP_PASSWORD}

# SMTP 상세 설정
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.naver.com
