CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login_id VARCHAR(10) NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(100) NOT NULL,
    is_email_verified BOOLEAN NOT NULL DEFAULT FALSE,
    nickname VARCHAR(10) NOT NULL,
    refresh_token VARCHAR(64),
    last_login_time TIMESTAMP,
    clear_progress_level INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_users_login_id UNIQUE (login_id),
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT uk_users_nickname UNIQUE (nickname)
);

CREATE TABLE dish (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    stage INTEGER NOT NULL,
    CONSTRAINT uk_dish_name UNIQUE (name),
    CONSTRAINT uk_dish_stage UNIQUE (stage),
    CONSTRAINT chk_dish_stage_positive CHECK (stage > 0)
);

CREATE TABLE email_verification (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    token VARCHAR(255) NOT NULL,
    expiration_time TIMESTAMP NOT NULL,
    last_sent_at TIMESTAMP NOT NULL,
    is_verified BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT uk_email_verification_email UNIQUE (email),
    CONSTRAINT uk_email_verification_token UNIQUE (token)
);

CREATE TABLE game_rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_name VARCHAR(20) NOT NULL,
    room_code VARCHAR(10) NOT NULL,
    current_level INTEGER DEFAULT 1,
    cook_book JSONB DEFAULT '[]'::jsonb,
    final_score INTEGER DEFAULT 0,
    start_time TIMESTAMP,
    end_time TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_game_rooms_room_code UNIQUE (room_code)
);

CREATE TABLE room_players (
    room_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    role_type VARCHAR(20) NOT NULL,
    joined_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (room_id, user_id),
    CONSTRAINT fk_room_players_room FOREIGN KEY (room_id) REFERENCES game_rooms(id),
    CONSTRAINT fk_room_players_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE user_dish (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    dish_id BIGINT NOT NULL,
    achievement_level INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_dish_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_user_dish_dish FOREIGN KEY (dish_id) REFERENCES dish(id),
    CONSTRAINT uk_user_dish_user_id_dish_id UNIQUE (user_id, dish_id),
    CONSTRAINT chk_user_dish_achievement_level CHECK (achievement_level BETWEEN 0 AND 2)
);
